### ISSUE TITLE
FAA Manufacturers/Models Correlation

### ISSUE THREAD

**Issue by jlpoolen** [RexKramer1/AircraftShapesSVG#1]
I'm working with data from the FAA (United States Federal Aviation Administration) data (download 60 MB zip from the FAA [here](https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download)), specifically the files:

- 181801502 May 24 23:23 MASTER.txt
- 228775    May 24 22:55 ENGINE.txt
- 14507208  May 24 22:51 ACFTREF.txt  [Aircraft Reference]

My strength is in computers and software, not aviation.  However, I have become focused on tracking and analyzing flight data and at a point where I'd like to add some icons to my chart and graphs.  I'm a big fan of SVG, built my own MapLibre Martin Vector Tile server for my mapping application which has a benefit of 3D -- somewhat experience.  

Any rate, I'm wondering what it would take to correlate you models and to set up something so any additional model tie into the FAA's records.  My models will be referencing past data and have the manufacturer model/engine combinations, so it would be great to know which SVG might come close to the aircraft being depicted.

I see in the HTML sample within this project some text description, i.e. "Learjet 35" or "UH-60 Black Hawk".  Do you have any, or possibly a code that ties into the FAA's coding system???

Note the FAA's Aircraft Reference, ACFTREF.txt (released May 24, 2024), has over 91,000 entries:
```
jlpoole@ryzdesk ~/adsb/FAA/20240527 $ cat ACFTREF.txt |wc -l
91818
jlpoole@ryzdesk ~/adsb/FAA/20240527 $
```

**Comment by RexKramer1** [comment]
Hi John, I downloaded and checked the FAA files. The FAA's coding system does not match with ICAO-typecodes, which I use as filename for the SVG files.

Maybe it is possible for you to use aircraft data from ICAO Doc8643 (https://www.icao.int/publications/DOC8643/Pages/Search.aspx) to get the ICAO typecodes using "manufacturer" and "model" from this document. You can download doc8643 data in csv-format from here: https://opensky-network.org/datasets/metadata/doc8643AircraftTypes.csv

Matching FAA type / model codes with ICAO typecodes looks like a great challenge for AI? Maybe it is worth a try.

**Comment by jlpoolen** [comment]
Thank you, @RexKramer1.  A valuable take-away is that you used a naming standard referencing publishing standard, e.g. ICAO.  Maybe that was in the documentation and I missed it in my glee to find this project.

 I downloaded the CSV with is 10,020 rows of data.  For convenience of future readers, the 7 column header of the CSV is is:
`AircraftDescription	Description	Designator	EngineCount	EngineType	ManufacturerCode	ModelFullName	WTC`

Now, to see how I might reconcile the ICAO classification with the FAA's classification which is about 9 times larger.
